disabled_rules:
  - closing_brace
  - opening_brace
  - identifier_name
  - type_name
  - force_try
  - force_cast
  - trailing_comma

included:
  - Source
  - Specs
excluded:
  - Carthage

line_length:
  warning: 200
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200
