fastlane_version "2.99.0"
fastlane_require 'dotenv'
Dotenv.load '.env'

default_platform :ios

import_from_git(
  url: "git@bitbucket.org:outware/autobahn.git",
  branch: "master",
  path: "Fastfile",
  version: "~> 1.0"
)

before_all do
  xcversion(version: "9.4.1")
end

platform :ios do

  desc "Cleans, tests, builds, computes code coverage and lints"
  override_lane :ci_dev do
    catalog_carthage
    clean
    test

    package_framework

    coverage
    lint
  end

  desc "Cleans and tests"
  override_lane :ci_qa do
    catalog_carthage
    clean
    test

    package_framework
  end

  desc "Cleans and tests"
  override_lane :ci_drop do
    catalog_carthage
    clean
    test

    package_framework
  end

  desc "Download required carthage dependencies"
  lane :catalog_carthage do
    Dir.chdir("../UIKitCatalog") do sh "carthage bootstrap --platform iOS --no-use-binaries" end
  end

  desc "Run `carthage build` to ensure the library can be packaged as a framework"
  lane :package_framework do
    Dir.chdir ".." do
      sh("/usr/local/bin/carthage", "build" ,"--no-skip-current", "--platform", "iOS")
    end
  end
end
