fastlane_version "2.99.0"
fastlane_require 'dotenv'
Dotenv.load '.env'

default_platform :ios

# If you have multiple Xcode version, you can uncomment the following line to
# choose which version to use:
#
# xcversion(version: "8.3.2")
# xcversion(version: "9.0")

import_from_git(
  url: "git@bitbucket.org:outware/autobahn.git",
  branch: "master",
  path: "Fastfile",
  version: "~> 1.0"
)

platform :ios do

  desc "Cleans, tests, builds, computes code coverage and lints"
  override_lane :ci_dev do
    clean
    test

    coverage
    lint
  end

  desc "Cleans and tests"
  override_lane :ci_qa do
    clean
    test
  end

  desc "Cleans and tests"
  override_lane :ci_drop do
    clean
    test
  end

end
