#!/bin/bash
#
# Description:
# This is a pre-commit hook that validates the files that are about to be
# committed by running a few checks:
# - Focused Tests
# - SwiftFormat
#
# Warnings: If any of those fails, the commit will be aborted.
#
################################################################################

################################################################################
# Methods
################################################################################

print_error_message() {
  error_message=$1

  echo ""
  echo "=========================="
  echo "= ERROR! Commit aborted! ="
  echo "=========================="
  echo ""
  echo "${error_message}"
  echo ""
  echo "If you believe this is a mistake, review the pre-commit script located in 'scripts/hooks/pre-commit'."
  echo ""
  exit 1
}

################################################################################
# Start of scripts
################################################################################

# Focused Tests (which uses the Quick testing framework)

focused_test=$(git diff --cached | grep -E "(fit|fcontext|fdescribe)\(\"")

if [[ ! -z ${focused_test} ]]; then
  echo ""
  echo "${focused_test}"
  print_error_message "Focused tests found! Please remove them from the tests staged for commit."
fi

# SwiftFormat

## Configure path

PATH="/usr/local/bin:$PATH"

## Ensure it is installed

if ! [[ -x $(command -v swiftformat) ]]; then
 echo 'Error: `swiftformat` is not installed. See `Documents/command-line-tools-installation.md` for more information.' >&2
 exit 1
fi

disabled_rules="redundantSelf,unusedArguments"

## Execute on the Source, Specs and Features directories

swiftformat_exit_codes=()

for folder in Source UIKitCatalog/Source UIKitCatalog/Features; do
  exit_code=$(swiftformat "${folder}" --disable ${disabled_rules} --indent 2 --wraparguments beforefirst | grep -q "completed. 0/"; echo $?)

  if [[ ${exit_code} -ne 0 ]]; then
    swiftformat_exit_codes+=(${exit_code})
  fi
done

## Report on code changes and prevent commit from proceeding

if ! [[ ${#swiftformat_exit_codes[@]} -eq 0 ]]; then
  print_error_message "Code formatted! Review the changes, stage & commit as necessary."
fi
